server.port=8080
server.error.include-stacktrace=ALWAYS 

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/investment_portfolio
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
